data_dir = '../saved_data/data_wow'
saved_dir = '../saved_data/t5-wow-rag'

class Arguments:
    train_file = f'{data_dir}/train_rag.json'
    valid_file = f'{data_dir}/dev.json'
    support_file = f'../saved_data/data_woi/train.json'
    do_train = True
    model_name_or_path = '../saved_data/t5-base-woi'
    max_source_length = 384
    max_target_length = 64
    learning_rate = 3e-5
    epoches = 1
    batch_size = 1
    gradient_accumulation_steps = 256
    report_steps = 50
    saved_steps = 200
    max_length = 64
    num_beams = 4
    topk = 10 # 10 for bm25
    bm25 = False
    threshold = 0. # 20. for bm25; 0.4 for rag; 16. bm25 lccc
    gap = 0.01 # 5. for bm25; 0.4 for rag; 4. bm25 lccc
    alpha = 0.1
    support_batch_size = 20
    do_support = False
    add_prefix = False
    lang = 'en'
    save_model = True
    random_seed = True
    output_dir = saved_dir
    predictions = f'{saved_dir}/generated_predictions.txt'
